import { Playfair_Display } from "@next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const playfair = Playfair_Display({
  weight: ["400", "700"], // You can choose the weights you need
  subsets: ["latin"], // Specify the language subset
  display: "swap", // Ensures text is visible while the font loads
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={playfair.className}>{children}</body>
    </html>
  );
}
